version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '20:00'
  target-branch: "4.x"
  open-pull-requests-limit: 20
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: '20:00'
  target-branch: "4.x"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '20:00'
  target-branch: "5.x"
  open-pull-requests-limit: 20
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: '20:00'
  target-branch: "5.x"
  open-pull-requests-limit: 20
