version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: '20:00'
